import type { Metadata, NextPage } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Auth Page Title",
  description: "Generated by create next app",
};

interface AuthLayoutProps {
  children: React.ReactNode;
}

const AuthLayout: NextPage<AuthLayoutProps> = ({ children }) => {
  return <>{children}</>;
};

export default AuthLayout;
