import type { Metadata, NextPage } from "next";
import "@/app/globals.css";
import Header from "@/components/layout/header/Header";
import SearchModal from "@/components/modals/SearchModal";
import NavigationList from "@/components/layout/NavigationList";
import NotificationModal from "@/components/modals/NotificationModal";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Main Page Title",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: React.ReactNode;
}

const MainLayout: NextPage<MainLayoutProps> = ({ children }) => {
  const isLeft = true;

  return (
    <>
      <Header />
      <div className={twMerge(["flex", !isLeft && "flex-row-reverse"])}>
        <NavigationList />
        {children}
        <NotificationModal />
      </div>
      <SearchModal />
    </>
  );
};

export default MainLayout;
