import type { Metadata, NextPage } from "next";
import "@/app/globals.css";
import Header from "@/app/components/layout/header/Header";
import SearchModal from "@/app/components/modals/SearchModal";
import NavigationList from "@/app/components/layout/NavigationList";
import NotificationList from "@/app/components/layout/NotificationList";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Main Page Title",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: React.ReactNode;
}

const MainLayout: NextPage<MainLayoutProps> = ({ children }) => {
  const isLeft = true;

  return (
    <>
      <Header />
      <div className={twMerge(["flex", !isLeft && "flex-row-reverse"])}>
        <NavigationList />
        {children}
        <NotificationList />
      </div>
      <SearchModal />
    </>
  );
};

export default MainLayout;
