import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: NextPage<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`bg-primary-gray dark:bg-dark-primary-gray ${inter.className}`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
