import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AuthStoreProvider } from "@/providers/auth-store-provider";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: NextPage<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`min-h-screen relative bg-primary-gray dark:bg-dark-primary-gray ${inter.className}`}
      >
        <AuthStoreProvider>
          <ThemeProvider attribute="class">
            {children}
          </ThemeProvider>
        </AuthStoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
