import Header from "@/app/components/header/Header";
import Footer from "@/app/components/footer/Footer";
import {Metadata, NextPage} from "next";

export const metadata: Metadata = {
    title: "Main Page Title",
    description: "Generated by create next app",
};

interface MainLayoutProps {
    children: React.ReactNode;
}

const GroupsLayout: NextPage<MainLayoutProps> = ({ children }) => {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    )
}

export default GroupsLayout;